"""empty message

Revision ID: 8c5fe5d5ce59
Revises: b9bf42648f85
Create Date: 2018-06-28 01:00:27.811446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5fe5d5ce59'
down_revision = 'b9bf42648f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_address', 'bucket_event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_address', 'bucket_event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
