"""empty message

Revision ID: 2c18989e2d49
Revises: 
Create Date: 2018-06-03 13:09:19.948186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c18989e2d49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucket',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('email_subject', sa.String(), nullable=True),
    sa.Column('email_content', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.drop_index('ix_email_timestamp', table_name='email')
    op.drop_table('email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('email_subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('event_id', name=u'email_pkey')
    )
    op.create_index('ix_email_timestamp', 'email', ['timestamp'], unique=False)
    op.drop_table('bucket')
    # ### end Alembic commands ###
