"""empty message

Revision ID: 310238428676
Revises: 53961004ea13
Create Date: 2018-06-05 14:55:16.178144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310238428676'
down_revision = '53961004ea13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bucket', ['event_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bucket', type_='unique')
    # ### end Alembic commands ###
