"""empty message

Revision ID: 53961004ea13
Revises: dd44b8e442ab
Create Date: 2018-06-05 14:51:51.598329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53961004ea13'
down_revision = 'dd44b8e442ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucket', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucket', 'created_date')
    # ### end Alembic commands ###
