"""empty message

Revision ID: a9ecef49f86b
Revises: 310238428676
Create Date: 2018-06-05 21:26:24.861068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ecef49f86b'
down_revision = '310238428676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bucket', 'email_content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bucket', 'email_subject',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bucket', 'event_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bucket', 'timestamp',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(u'bucket_event_id_key', 'bucket', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'bucket_event_id_key', 'bucket', ['event_id'])
    op.alter_column('bucket', 'timestamp',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bucket', 'event_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bucket', 'email_subject',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bucket', 'email_content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
