"""empty message

Revision ID: ac5a86f7f6d7
Revises: 2c18989e2d49
Create Date: 2018-06-05 12:59:36.776850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5a86f7f6d7'
down_revision = '2c18989e2d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucket', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('bucket', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bucket', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('bucket', 'id')
    # ### end Alembic commands ###
